services:
  backend:
    build:
      dockerfile: ./Dockerfile-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/.venv/
  frontend:
    build:
      dockerfile: ./Dockerfile-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vue-project:/app/frontend/vue-project
      - /app/node_modules/
